### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by navierula** [cjnoodle/pwp-capstones#3]
Valid Python Code (4/4)
Code included runs without any errors.

Implementation of Project Requirements (4/4)
Code produces the suite of functions and classes required of it and calls them in an appropriate order.

Software Architecture (4/4)
Code is separated into distinct classes and functions each which are invoked for their own purposes. 

Uses Python Language Features (4/4)
Code uses language features appropriately. If a task can be solved with a Python language feature, it is.

Overall, great job! Your code was clean, well-commented, and ran without errors.

**Comment by cjnoodle** [comment]
Thanks, navierula.
